version: '3.8'

services:
  database:
    image: postgres:15-alpine
    container_name: decskill-db
    hostname: decskill-db
    ports:
      - ${DB_PORT}:5432
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      TZ: Europe/Madrid
      PGTZ: Europe/Madrid
    restart: unless-stopped
    tty: true

  backend:
    container_name: decskill-be
    hostname: decskill-be
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_PATH: ${JAR_PATH}
        API_PORT: ${API_PORT}
    ports:
      - ${API_PORT}:3000
    depends_on:
      - database
    restart: unless-stopped
    tty: true
